# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "25fe1eb8113a4ffe32866781ed8bdd23"
name = "YMM-Fitment"
application_url = "https://ymm-fitment-production.up.railway.app/app"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_inventory,write_products"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://ymm-fitment-production.up.railway.app/auth/callback",
  "https://ymm-fitment-production.up.railway.app/auth/shopify/callback",
  "https://ymm-fitment-production.up.railway.app/api/auth/callback"
]

[pos]
embedded = false
